apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdemo
  labels:
    app: nodejsdemo
    component: demoapp
spec:
  selector:
    matchLabels:
      app: nodejsdemo
      component: demoapp
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejsdemo
        component: demoapp
    spec:
       containers:
       - name: nodejsdemo
         image: hrexed/nodejsk8s:sqlcommenter_0.1
         imagePullPolicy: Always
         env:
         - name: NODE_ENV
           value: "development"
         - name: PORT
           value: "3000"
         - name: GOOGLE_APPLICATION_CREDENTIALS
           value: /secrets/service_account.json
         - name: POSTGRES_HOST
           value: "localhost"
         - name: POSTGRES_PORT
           value: "5432"
         - name: POSTGRES_USER
           valueFrom:
             secretKeyRef:
               name: postgres-credentials
               key: username
         - name: POSTGRES_PASSWORD
           valueFrom:
             secretKeyRef:
               name: postgres-credentials
               key: password
         - name: OTLP_COLLECTOR_HOST
           value: "otlp-collector"
         - name: OTLP_COLLECTOR_PORT
           value: "55680"
         volumeMounts:
           - name: sqlcommenter-secret
             mountPath: /secrets/
             readOnly: true
       - name: cloud-sql-proxy
         # It is recommended to use the latest version of the Cloud SQL proxy
         # Make sure to update on a regular schedule!
         image: gcr.io/cloudsql-docker/gce-proxy:1.17
         command:
           - "/cloud_sql_proxy"
           # If connecting from a VPC-native GKE cluster, you can use the
           # following flag to have the proxy connect over private IP
           # - "-ip_address_types=PRIVATE"
           # Replace DB_PORT with the port the proxy should listen on
           # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
           - "-instances=CLOUDSQL_INSTANCE_TOREPLACE=tcp:5432"
           - "-credential_file=/secrets/service_account.json"
         securityContext:
           # The default Cloud SQL proxy image runs as the
           # "nonroot" user and group (uid: 65532) by default.
           runAsNonRoot: true
         volumeMounts:
           - name: sqlcommenter-secret
             mountPath: /secrets/
             readOnly: true
         resources:
           requests:
             # The proxy's memory use scales linearly with the number of active
             # connections. Fewer open connections will use less memory. Adjust
             # this value based on your application's requirements.
             memory: "2Gi"
             # The proxy's CPU use scales linearly with the amount of IO between
             # the database and the application. Adjust this value based on your
             # application's requirements.
             cpu: "1"
       volumes:
       - name: sqlcommenter-secret
         secret:
           secretName: sa-sqlcommenter
       restartPolicy: Always

