apiVersion: v1
kind: Service
metadata:
  name: nodejsdemo
  labels:
    app: nodejsdemo
  namespace: sqlcommenter
spec:
  selector:
    app: nodejsdemo
  type: LoadBalancer
  ports:
    - port: 3000

