apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nodejschart.fullname" . }}-secret
  labels:
    app: {{ template "nodejschart.name" . }}
    chart: {{ template "nodejschart.chart" . }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-35"  
type: Opaque
data:
  user: {{ .Values.secret.user }}
  password: {{ .Values.secret.password }}