apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejschart.fullname" . }}
  labels:
{{ include "nodejschart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "nodejschart.name" . }}
    release: {{ .Release.Name }}